version: '3.8'  # 指定Compose版本
services:
  nginx:  # 服务名称
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html/src
      - /root/.well-known/pki-validation/:/root/.well-known/pki-validation  # 添加只读权限
    restart: unless-stopped
